//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_TranDau
    {
        public string MaTD { get; set; }
        public string MaDoi { get; set; }
        public Nullable<int> SoBanThang { get; set; }
    
        public virtual Doi Doi { get; set; }
    }
}
