//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test1.App_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBDEntities : DbContext
    {
        public QLBDEntities()
            : base("name=QLBDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CT_TranDau> CT_TranDau { get; set; }
        public virtual DbSet<Doi> Dois { get; set; }
        public virtual DbSet<San> Sans { get; set; }
        public virtual DbSet<TranDau> TranDaus { get; set; }
    }
}
